[strip-0]
limit = 12
label = ""

[strip-1]
limit = 12
label = ""

[strip-2]
A1 = true
A2 = true
A3 = true
A4 = true
A5 = true
B1 = true
B2 = true
B3 = true
mono = true
solo = true
mute = true
limit = 12
label = ""

[strip-3]
limit = 12
label = ""

[strip-4]
limit = 12
label = ""

[strip-5]
limit = 12
label = ""

[strip-6]
limit = 12
label = ""

[strip-7]
limit = 12
label = ""
